language: node_js

node_js:
  - stable
  - 10
  - 8

addons:
  sonarcloud:
    organization: han-feng-github
    token:
      secure: $SONAR_CLOUD_TOKEN

script:
  - npm run build:travis
  - npm test

jobs:
  include:
    - stage: Deploy to Github
      node_js: stable
      deploy:
        provider: pages
        local-dir: target/dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
    - stage: QA Report
      node_js: stable
      script:
        - npx codecov --token=$CODECOV_TOKEN
        - sonar-scanner
